---
- hosts: all
  become: yes
  name: "Set hostnames for all hosts"
  tasks:
  - name: Set hostname
    shell: hostnamectl set-hostname {{ inventory_hostname }}
  - name: Renew DHCP
    shell: dhclient -r; dhclient