all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" 

  children:
    k8s_controllers:
      hosts:
        us20-71bb31381ab1e05b.k8s.dylanlab.xyz:
        us20-885613bd77f87422.k8s.dylanlab.xyz:
        us20-c075adb37fa168fd.k8s.dylanlab.xyz:
        us20-3bcb8830e2df65c6.k8s.dylanlab.xyz:
        us20-d839d22448c1c3fa.k8s.dylanlab.xyz:

    k8s_workers:
      hosts:
        us20-59a435e1df8204a9.k8s.dylanlab.xyz:
        us20-0231325d96098500.k8s.dylanlab.xyz:
        us20-932f53fbb357a9e3.k8s.dylanlab.xyz:
        us20-be6e097f91b63052.k8s.dylanlab.xyz:
        us20-23ee3bcc2181d617.k8s.dylanlab.xyz:
